name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.6.10, 3.0, 3.1, 3.2, 3.3.5, 3.3.6]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Remove Gemfile.lock
      run: rm -f Gemfile.lock
    - name: Install dependencies
      run: |
        gem install bundler -v 2.2.3
        bundle config set --local without 'development'
        bundle install
    - name: Run tests
      run: bundle exec rspec
